dataset:
- 20NewsGroups
solver:
- JDOT_SVC:
    param_grid:
    - jdotclassifier__alpha:
      - 0.1
      - 0.3
      - 0.5
      - 0.7
      - 0.9
      jdotclassifier__base_estimator__estimator_name:
      - SVC_C10.0_Gamma10.0
      jdotclassifier__n_iter_max:
      - 100
      jdotclassifier__thr_weights:
      - 1.0e-07
      jdotclassifier__tol:
      - 1.0e-06
