dataset:
- OfficeHomeResnet
solver:
- JDOT_SVC:
    param_grid:
    - jdotclassifier__alpha:
      - 0.5
      jdotclassifier__base_estimator__estimator_name:
      - SVC_C10.0_Gamma0.001
      jdotclassifier__n_iter_max:
      - 3
      jdotclassifier__thr_weights:
      - 1.0e-07
      jdotclassifier__tol:
      - 1.0e-06
