dataset:
- Office31
solver:
- subspace_alignment:
    param_grid:
    - finalestimator__estimator_name:
      - LR_C0.01
      subspacealignmentadapter__n_components:
      - 1
      - 2
      - 5
      - 10
      - 20
      - 50
      - 100
