dataset:
- 20NewsGroups
solver:
- nearest_neighbor_reweight:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma10.0
      nearestneighborreweightadapter__laplace_smoothing:
      - true
      - false
      nearestneighborreweightadapter__n_neighbors:
      - 1
