dataset:
- Office31
solver:
- nearest_neighbor_reweight:
    param_grid:
    - finalestimator__estimator_name:
      - LR_C0.01
      nearestneighborreweightadapter__laplace_smoothing:
      - true
      - false
      nearestneighborreweightadapter__n_neighbors:
      - 1
