dataset:
- Phishing
solver:
- nearest_neighbor_reweight:
    param_grid:
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.65_maxdepth20
      nearestneighborreweightadapter__laplace_smoothing:
      - true
      - false
      nearestneighborreweightadapter__n_neighbors:
      - 1
