dataset:
- Simulated
solver:
- nearest_neighbor_reweight:
    param_grid:
    - finalestimator__estimator_name:
      - SVC
      nearestneighborreweightadapter__laplace_smoothing:
      - true
      - false
      nearestneighborreweightadapter__n_neighbors:
      - 1
