dataset:
- 20NewsGroups
solver:
- KMM:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma10.0
      kmmreweightadapter__B:
      - 1000.0
      kmmreweightadapter__gamma:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1.0
      - 10.0
      - 100.0
      - 1000.0
      - null
      kmmreweightadapter__max_iter:
      - 1000
      kmmreweightadapter__smooth_weights:
      - false
      kmmreweightadapter__tol:
      - 1.0e-06
