dataset:
- Office31
solver:
- linear_ot_mapping:
    param_grid:
    - finalestimator__estimator_name:
      - LR_C0.01
      linearotmappingadapter__bias:
      - true
      - false
      linearotmappingadapter__reg:
      - 1.0e-08
      - 1.0e-06
      - 0.1
      - 1
      - 10
