dataset:
- 20NewsGroups
solver:
- TarS:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma10.0
      mmdtarsreweightadapter__gamma:
      - 0.0001
      - 0.001
      - 0.01
      - 0.1
      - 1.0
      - 10.0
      - 100.0
      - 1000.0
      - null
      mmdtarsreweightadapter__max_iter:
      - 1000
      mmdtarsreweightadapter__reg:
      - 1.0e-06
      mmdtarsreweightadapter__tol:
      - 1.0e-06
