dataset:
- 20NewsGroups
solver:
- MMDSConS:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma10.0
      mmdlsconsmappingadapter__gamma:
      - 1
      mmdlsconsmappingadapter__max_iter:
      - 4
      mmdlsconsmappingadapter__reg_k:
      - 1.0e-08
      mmdlsconsmappingadapter__reg_m:
      - 1.0e-08
      mmdlsconsmappingadapter__tol:
      - 1.0e-05
