dataset:
- AmazonReview
solver:
- MMDSConS:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C1000.0_Gamma0.001
      mmdlsconsmappingadapter__gamma:
      - 0.1
      - 1
      - 10
      mmdlsconsmappingadapter__max_iter:
      - 100
      mmdlsconsmappingadapter__reg_k:
      - 1.0e-10
      - 1.0e-08
      mmdlsconsmappingadapter__reg_m:
      - 1.0e-10
      - 1.0e-08
      mmdlsconsmappingadapter__tol:
      - 1.0e-05
