dataset:
- Office31
solver:
- MMDSConS:
    param_grid:
    - finalestimator__estimator_name:
      - LR_C0.01
      mmdlsconsmappingadapter__gamma:
      - 0.01
      - 0.1
      - 1
      - 10
      - 100
      mmdlsconsmappingadapter__max_iter:
      - 20
      mmdlsconsmappingadapter__reg_k:
      - 1.0e-08
      mmdlsconsmappingadapter__reg_m:
      - 1.0e-08
      mmdlsconsmappingadapter__tol:
      - 1.0e-05
