dataset:
- Phishing
solver:
- MMDSConS:
    param_grid:
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.65_maxdepth20
      mmdlsconsmappingadapter__gamma:
      - 0.1
      - 1
      - 10
      mmdlsconsmappingadapter__max_iter:
      - 100
      mmdlsconsmappingadapter__reg_k:
      - 1.0e-10
      - 1.0e-08
      mmdlsconsmappingadapter__reg_m:
      - 1.0e-10
      - 1.0e-08
      mmdlsconsmappingadapter__tol:
      - 1.0e-05
