dataset:
- AmazonReview
solver:
- gaussian_reweight:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C1000.0_Gamma0.001
      gaussianreweightadapter__reg:
      - auto
      - 1.0e-05
      - 0.01
      - 0.5
