dataset:
- mnist_usps
solver:
- gaussian_reweight:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma0.01
      gaussianreweightadapter__reg:
      - auto
      - 1.0e-05
      - 0.01
      - 0.5
