dataset:
- Office31
solver:
- gaussian_reweight:
    param_grid:
    - finalestimator__estimator_name:
      - LR_C0.01
      gaussianreweightadapter__reg:
      - auto
      - 1.0e-05
      - 0.01
      - 0.5
