dataset:
- Phishing
solver:
- gaussian_reweight:
    param_grid:
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.65_maxdepth20
      gaussianreweightadapter__reg:
      - auto
      - 1.0e-05
      - 0.01
      - 0.5
