dataset:
- mnist_usps
n-repetitions: 1
solver:
- class_regularizer_ot_mapping:
    param_grid:
      classregularizerotmappingadapter__max_inner_iter:
      - 100
      classregularizerotmappingadapter__max_iter:
      - 100
      classregularizerotmappingadapter__metric:
      - sqeuclidean
      classregularizerotmappingadapter__norm:
      - lpl1
      - l1l2
      classregularizerotmappingadapter__reg_cl:
      - 0.1
      - 0.01
      classregularizerotmappingadapter__reg_e:
      - 1.0
      - 0.1
      classregularizerotmappingadapter__tol:
      - 1.0e-08
      finalestimator__estimator_name:
      - &LR LR_C1.0
      - &SVC SVC_C1.0_Gamma0.1
      - &XGB XGB_subsample0.5_colsample0.5_maxdepth6
- CORAL:
    param_grid:
      coraladapter__reg:
      - auto
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
- DASVM:
    param_grid:
      dasvmclassifier__k:
      - 3
      - 5
      - 7
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
- density_reweight:
    param_grid:
      densityreweightadapter__weight_estimator__bandwidth:
      - 0.01
      - 0.1
      - 1.0
      - 10.0
      - 100.0
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
- discriminator_reweight:
    param_grid:
      discriminatorreweightadapter__domain_classifier__estimator_name:
      - LR
      - SVC
      - KNN
      - XGB
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
- entropic_ot_mapping:
    param_grid:
      entropicotmappingadapter__max_iter:
      - 1000
      entropicotmappingadapter__metric:
      - sqeuclidean
      entropicotmappingadapter__norm:
      - null
      - median
      - max
      entropicotmappingadapter__reg_e:
      - 1
      - 10
      entropicotmappingadapter__tol:
      - 1.0e-08
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
- gaussian_reweight:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      gaussianreweightadapter__reg:
      - auto
      - 1.0e-05
      - 0.01
      - 0.5
- JDOT_SVC:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      jdotclassifier__alpha:
      - 0.1
      - 0.3
      - 0.5
      - 0.7
      - 0.9
      jdotclassifier__n_iter_max:
      - 100
      jdotclassifier__thr_weights:
      - 1.0e-07
      jdotclassifier__tol:
      - 1.0e-06
- KLIEP:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      kliepreweightadapter__cv:
      - 5
      kliepreweightadapter__gamma:
      - 0.01
      - 0.1
      - 1.0
      - 10.0
      - 100.0
      - auto
      - scale
      kliepreweightadapter__max_iter:
      - 1000
      kliepreweightadapter__n_centers:
      - 100
      - 1000
      kliepreweightadapter__random_state:
      - 0
      kliepreweightadapter__tol:
      - 1.0e-06
- KMM:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      kmmreweightadapter__B:
      - 1000.0
      kmmreweightadapter__gamma:
      - 0.01
      - 0.1
      - 1.0
      - 10.0
      - 100.0
      kmmreweightadapter__max_iter:
      - 1000
      kmmreweightadapter__smooth_weights:
      - false
      kmmreweightadapter__tol:
      - 1.0e-06
- linear_ot_mapping:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      linearotmappingadapter__bias:
      - true
      - false
      linearotmappingadapter__reg:
      - 1.0e-08
      - 1.0e-06
      - 0.1
      - 1
      - 10
- MMDSConS:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      mmdlsconsmappingadapter__gamma:
      - 0.1
      - 1
      - 10
      mmdlsconsmappingadapter__max_iter:
      - 100
      mmdlsconsmappingadapter__reg_k:
      - 1.0e-10
      - 1.0e-08
      mmdlsconsmappingadapter__reg_m:
      - 1.0e-10
      - 1.0e-08
      mmdlsconsmappingadapter__tol:
      - 1.0e-05
- nearest_neighbor_reweight:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      nearestneighborreweightadapter__laplace_smoothing:
      - true
      - false
      nearestneighborreweightadapter__n_neighbors:
      - 1
- NO_DA_SOURCE_ONLY:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
- NO_DA_SOURCE_ONLY_BASE_ESTIM:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
- NO_DA_TARGET_ONLY:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
- OTLabelProp:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      otlabelpropadapter__metric:
      - sqeuclidean
      - euclidean
      otlabelpropadapter__reg:
      - null
      - 0.1
- ot_mapping:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      otmappingadapter__max_iter:
      - 100000
      otmappingadapter__metric:
      - sqeuclidean
      otmappingadapter__norm:
      - null
      - median
      - max
- PCA:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      pca__n_components:
      - 1
      - 2
      - 5
      - 10
      - 20
      - 50
      - 100
- subspace_alignment:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      subspacealignmentadapter__n_components:
      - 1
      - 2
      - 5
      - 10
      - 20
      - 50
      - 100
- TarS:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      mmdtarsreweightadapter__gamma:
      - 0.1
      - 1
      - 10
      mmdtarsreweightadapter__max_iter:
      - 1000
      mmdtarsreweightadapter__reg:
      - 1.0e-10
      - 1.0e-08
      - 1.0e-06
      mmdtarsreweightadapter__tol:
      - 1.0e-06
      - 0.0001
- transfer_component_analysis:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      transfercomponentanalysisadapter__kernel:
      - rbf
      transfercomponentanalysisadapter__mu:
      - 10
      - 100
      transfercomponentanalysisadapter__n_components:
      - 1
      - 2
      - 5
      - 10
      - 20
      - 50
      - 100
- transfer_joint_matching:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      transferjointmatchingadapter__kernel:
      - rbf
      transferjointmatchingadapter__n_components:
      - 1
      - 2
      - 5
      - 10
      - 20
      - 50
      - 100
      transferjointmatchingadapter__tradeoff:
      - 0
      - 0.0001
      - 0.01
- transfer_subspace_learning:
    param_grid:
      finalestimator__estimator_name:
      - *LR
      - *SVC
      - *XGB
      transfersubspacelearningadapter__base_method:
      - flda
      transfersubspacelearningadapter__length_scale:
      - 2
      transfersubspacelearningadapter__max_iter:
      - 300
      transfersubspacelearningadapter__mu:
      - 0.1
      - 1
      - 10
      transfersubspacelearningadapter__n_components:
      - 1
      - 2
      - 5
      - 10
      - 20
      - 50
      - 100
      transfersubspacelearningadapter__reg:
      - 0.0001
      transfersubspacelearningadapter__tol:
      - 0.0001
