20NewsGroups:
  Best: SVC_C10.0_Gamma10.0
  BestSVC: SVC_C10.0_Gamma10.0
AmazonReview:
  Best: SVC_C1000.0_Gamma0.001
  BestSVC: SVC_C1000.0_Gamma0.001
BCI:
  Best: LR_C2.0
  BestSVC: SVC_C10.0_Gamma0.1
Mushrooms:
  Best: LR
  BestSVC: SVC
Office31:
  Best: LR_C0.01
  BestSVC: SVC
OfficeHomeResnet:
  Best: SVC_C10.0_Gamma0.001
  BestSVC: SVC_C10.0_Gamma0.001
Phishing:
  Best: XGB_subsample0.8_colsample0.65_maxdepth20
  BestSVC: SVC_C10.0_Gamma0.1
Simulated:
  Best: SVC
  BestSVC: SVC
mnist_usps:
  Best: SVC_C10.0_Gamma0.01
  BestSVC: SVC_C10.0_Gamma0.01
