# This is an example of a configuration file for the experiments

# We define the solvers
solver:
  - NO_DA_SOURCE_ONLY

# We define the datasets
dataset:
  - 20NewsGroups[max_features=5, source_target=[('rec', 'talk')]]

max-runs: 0
