# This is an example of a configuration file for the experiments

# We define the solvers
solver:
  - NO_DA_SOURCE_ONLY
  - NO_DA_TARGET_ONLY
  - CORAL

# We define the datasets
dataset:
  - mnist_usps
