# This is an example of a configuration file to launch the experiments on a SLURM cluster
# Before running the experiments, you need to change the following parameters:
# - mail-user: the email address to receive notifications
# - source activate env_name: the name of the conda environment to activate

slurm_time: 09:59:00        # max runtime 10 hours
slurm_additional_parameters:
  job-name: skada-bench # Job name
  output: slurm_output.txt # Output file
  partition: normal,parietal
  mail-type: ALL
  mail-user: name@email.com # TO CHANGE TO YOUR EMAIL
  ntasks: 1                 # Number of tasks per job
  cpus-per-task: 1         # requires 1 CPUs per job
slurm_setup:  # sbatch script commands added before the main job
  - module purge
  - echo "current directory is $(pwd)"
  - module load anaconda3
  - source activate env # TO CHANGE TO YOUR ENVIRONMENT NAME
