dataset:
- AmazonReview
- BCI
- Mushrooms
- mnist_usps[n_samples_source=10000,n_samples_target=10000]
- mnist_usps[n_samples_source=3000,n_samples_target=3000]
- Office31
- OfficeHomeResnet
- Phishing
- 20NewsGroups
n-repetitions: 1
solver:
  NO_DA_SOURCE_ONLY_BASE_ESTIM:
    param_grid:
    - finalestimator__estimator_name:
      - LR
    - finalestimator__estimator_name:
      - SVC
    - finalestimator__estimator_name:
      - XGB
    - finalestimator__estimator_name:
      - LR_C0.001
    - finalestimator__estimator_name:
      - LR_C0.002
    - finalestimator__estimator_name:
      - LR_C0.005
    - finalestimator__estimator_name:
      - LR_C0.01
    - finalestimator__estimator_name:
      - LR_C0.02
    - finalestimator__estimator_name:
      - LR_C0.05
    - finalestimator__estimator_name:
      - LR_C0.1
    - finalestimator__estimator_name:
      - LR_C0.2
    - finalestimator__estimator_name:
      - LR_C0.5
    - finalestimator__estimator_name:
      - LR_C1.0
    - finalestimator__estimator_name:
      - LR_C2.0
    - finalestimator__estimator_name:
      - LR_C5.0
    - finalestimator__estimator_name:
      - LR_C10.0
    - finalestimator__estimator_name:
      - LR_C20.0
    - finalestimator__estimator_name:
      - LR_C50.0
    - finalestimator__estimator_name:
      - LR_C100.0
    - finalestimator__estimator_name:
      - LR_C200.0
    - finalestimator__estimator_name:
      - LR_C500.0
    - finalestimator__estimator_name:
      - LR_C1000.0
    - finalestimator__estimator_name:
      - SVC_C0.001_Gamma0.001
    - finalestimator__estimator_name:
      - SVC_C0.001_Gamma0.01
    - finalestimator__estimator_name:
      - SVC_C0.001_Gamma0.1
    - finalestimator__estimator_name:
      - SVC_C0.001_Gamma1.0
    - finalestimator__estimator_name:
      - SVC_C0.001_Gamma10.0
    - finalestimator__estimator_name:
      - SVC_C0.001_Gamma100.0
    - finalestimator__estimator_name:
      - SVC_C0.001_Gamma1000.0
    - finalestimator__estimator_name:
      - SVC_C0.01_Gamma0.001
    - finalestimator__estimator_name:
      - SVC_C0.01_Gamma0.01
    - finalestimator__estimator_name:
      - SVC_C0.01_Gamma0.1
    - finalestimator__estimator_name:
      - SVC_C0.01_Gamma1.0
    - finalestimator__estimator_name:
      - SVC_C0.01_Gamma10.0
    - finalestimator__estimator_name:
      - SVC_C0.01_Gamma100.0
    - finalestimator__estimator_name:
      - SVC_C0.01_Gamma1000.0
    - finalestimator__estimator_name:
      - SVC_C0.1_Gamma0.001
    - finalestimator__estimator_name:
      - SVC_C0.1_Gamma0.01
    - finalestimator__estimator_name:
      - SVC_C0.1_Gamma0.1
    - finalestimator__estimator_name:
      - SVC_C0.1_Gamma1.0
    - finalestimator__estimator_name:
      - SVC_C0.1_Gamma10.0
    - finalestimator__estimator_name:
      - SVC_C0.1_Gamma100.0
    - finalestimator__estimator_name:
      - SVC_C0.1_Gamma1000.0
    - finalestimator__estimator_name:
      - SVC_C1.0_Gamma0.001
    - finalestimator__estimator_name:
      - SVC_C1.0_Gamma0.01
    - finalestimator__estimator_name:
      - SVC_C1.0_Gamma0.1
    - finalestimator__estimator_name:
      - SVC_C1.0_Gamma1.0
    - finalestimator__estimator_name:
      - SVC_C1.0_Gamma10.0
    - finalestimator__estimator_name:
      - SVC_C1.0_Gamma100.0
    - finalestimator__estimator_name:
      - SVC_C1.0_Gamma1000.0
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma0.001
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma0.01
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma0.1
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma1.0
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma10.0
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma100.0
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma1000.0
    - finalestimator__estimator_name:
      - SVC_C100.0_Gamma0.001
    - finalestimator__estimator_name:
      - SVC_C100.0_Gamma0.01
    - finalestimator__estimator_name:
      - SVC_C100.0_Gamma0.1
    - finalestimator__estimator_name:
      - SVC_C100.0_Gamma1.0
    - finalestimator__estimator_name:
      - SVC_C100.0_Gamma10.0
    - finalestimator__estimator_name:
      - SVC_C100.0_Gamma100.0
    - finalestimator__estimator_name:
      - SVC_C100.0_Gamma1000.0
    - finalestimator__estimator_name:
      - SVC_C1000.0_Gamma0.001
    - finalestimator__estimator_name:
      - SVC_C1000.0_Gamma0.01
    - finalestimator__estimator_name:
      - SVC_C1000.0_Gamma0.1
    - finalestimator__estimator_name:
      - SVC_C1000.0_Gamma1.0
    - finalestimator__estimator_name:
      - SVC_C1000.0_Gamma10.0
    - finalestimator__estimator_name:
      - SVC_C1000.0_Gamma100.0
    - finalestimator__estimator_name:
      - SVC_C1000.0_Gamma1000.0
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.5_maxdepth3
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.5_maxdepth6
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.5_maxdepth10
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.5_maxdepth20
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.65_maxdepth3
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.65_maxdepth6
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.65_maxdepth10
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.65_maxdepth20
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.8_maxdepth3
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.8_maxdepth6
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.8_maxdepth10
    - finalestimator__estimator_name:
      - XGB_subsample0.5_colsample0.8_maxdepth20
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.5_maxdepth3
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.5_maxdepth6
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.5_maxdepth10
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.5_maxdepth20
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.65_maxdepth3
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.65_maxdepth6
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.65_maxdepth10
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.65_maxdepth20
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.8_maxdepth3
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.8_maxdepth6
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.8_maxdepth10
    - finalestimator__estimator_name:
      - XGB_subsample0.65_colsample0.8_maxdepth20
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.5_maxdepth3
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.5_maxdepth6
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.5_maxdepth10
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.5_maxdepth20
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.65_maxdepth3
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.65_maxdepth6
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.65_maxdepth10
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.65_maxdepth20
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.8_maxdepth3
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.8_maxdepth6
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.8_maxdepth10
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.8_maxdepth20
