# This is an example of a configuration file to launch the experiments on a SLURM cluster
# Before running the experiments, you need to change the following parameters:
# - mail-user: the email address to receive notifications
# - source activate env_name: the name of the conda environment to activate

# slurm_time: 7-00:00:00        # max runtime 7 days
slurm_additional_parameters:
  job-name: skada-bench # Job name
  output: slurm_output.txt # Output file
  partition: normal,parietal
  mail-type: ALL
  mail-user: theo.gnassounou@inria.fr # TO CHANGE TO YOUR EMAIL
  ntasks: 1                 # Number of tasks per job
  cpus-per-task: 5         # requires 5 CPUs per job
slurm_setup:  # sbatch script commands added before the main job
  - module purge
  - echo "current directory is $(pwd)"
  - module load anaconda3
  - source activate skada-bench # TO CHANGE TO YOUR ENVIRONMENT NAME
