dataset:
- mnist_usps
solver:
- density_reweight:
    param_grid:
    - densityreweightadapter__weight_estimator__bandwidth:
      - 0.01
      - 0.1
      - 1.0
      - 10.0
      - 100.0
      - scott
      - silverman
      finalestimator__estimator_name:
      - SVC_C10.0_Gamma0.01
