dataset:
- Office31
solver:
- density_reweight:
    param_grid:
    - densityreweightadapter__weight_estimator__bandwidth:
      - 0.01
      - 0.1
      - 1.0
      - 10.0
      - 100.0
      - scott
      - silverman
      finalestimator__estimator_name:
      - LR_C0.01
