dataset:
- OfficeHomeResnet
solver:
- transfer_component_analysis:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma0.001
      transfercomponentanalysisadapter__kernel:
      - rbf
      transfercomponentanalysisadapter__mu:
      - 10
      - 100
      transfercomponentanalysisadapter__n_components:
      - 5
      - 10
      - 20
