dataset:
- mnist_usps
solver:
- transfer_subspace_learning:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma0.01
      transfersubspacelearningadapter__base_method:
      - flda
      transfersubspacelearningadapter__length_scale:
      - 2
      transfersubspacelearningadapter__max_iter:
      - 4
      transfersubspacelearningadapter__mu:
      - 1
      transfersubspacelearningadapter__n_components:
      - 5
      - 10
      - 20
      transfersubspacelearningadapter__reg:
      - 0.0001
      transfersubspacelearningadapter__tol:
      - 0.0001
