dataset:
- BCI
solver:
- entropic_ot_mapping:
    param_grid:
    - entropicotmappingadapter__max_iter:
      - 1000
      entropicotmappingadapter__metric:
      - sqeuclidean
      - cosine
      - cityblock
      entropicotmappingadapter__norm:
      - median
      entropicotmappingadapter__reg_e:
      - 0.1
      - 0.5
      - 1.0
      entropicotmappingadapter__tol:
      - 1.0e-06
      finalestimator__estimator_name:
      - LR_C2.0
