dataset:
- OfficeHomeResnet
solver:
- ot_mapping:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma0.001
      otmappingadapter__max_iter:
      - 1000000
      otmappingadapter__metric:
      - sqeuclidean
      - cosine
      - cityblock
      otmappingadapter__norm:
      - median
