dataset:
- Phishing
solver:
- ot_mapping:
    param_grid:
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.65_maxdepth20
      otmappingadapter__max_iter:
      - 1000000
      otmappingadapter__metric:
      - sqeuclidean
      - cosine
      - cityblock
      otmappingadapter__norm:
      - median
