dataset:
- Office31
solver:
- discriminator_reweight:
    param_grid:
    - discriminatorreweightadapter__domain_classifier__estimator_name:
      - LR
      - SVC
      - KNN
      - XGB
      finalestimator__estimator_name:
      - LR_C0.01
