dataset:
- AmazonReview
solver:
- OTLabelProp:
    param_grid:
    - - finalestimator__estimator_name:
        - SVC_C1000.0_Gamma0.001
        otlabelpropadapter__metric:
        - sqeuclidean
        - cosine
        - cityblock
        otlabelpropadapter__n_iter_max:
        - 10000
        otlabelpropadapter__reg:
        - null
      - finalestimator__estimator_name:
        - SVC_C1000.0_Gamma0.001
        otlabelpropadapter__metric:
        - sqeuclidean
        - cosine
        - cityblock
        otlabelpropadapter__n_iter_max:
        - 100
        otlabelpropadapter__reg:
        - 0.1
        - 1
