dataset:
- BCI
solver:
- OTLabelProp:
    param_grid:
    - - finalestimator__estimator_name:
        - LR_C2.0
        otlabelpropadapter__metric:
        - sqeuclidean
        - cosine
        - cityblock
        otlabelpropadapter__n_iter_max:
        - 10000
        otlabelpropadapter__reg:
        - null
      - finalestimator__estimator_name:
        - LR_C2.0
        otlabelpropadapter__metric:
        - sqeuclidean
        - cosine
        - cityblock
        otlabelpropadapter__n_iter_max:
        - 100
        otlabelpropadapter__reg:
        - 0.1
        - 1
