dataset:
- Office31
solver:
- OTLabelProp:
    param_grid:
    - finalestimator__estimator_name:
      - LR_C0.01
      otlabelpropadapter__metric:
      - sqeuclidean
      - cosine
      - cityblock
      otlabelpropadapter__reg:
      - null
      - 0.1
      - 1.0
