dataset:
- OfficeHomeResnet
solver:
- OTLabelProp:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C10.0_Gamma0.001
      otlabelpropadapter__metric:
      - sqeuclidean
      - cosine
      - cityblock
      otlabelpropadapter__reg:
      - null
      - 0.1
      - 1.0
