dataset:
- Phishing
solver:
- OTLabelProp:
    param_grid:
    - finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.65_maxdepth20
      otlabelpropadapter__metric:
      - sqeuclidean
      - cosine
      - cityblock
      otlabelpropadapter__reg:
      - null
      - 0.1
      - 1.0
