dataset:
- Simulated
solver:
- OTLabelProp:
    param_grid:
    - finalestimator__estimator_name:
      - SVC
      otlabelpropadapter__metric:
      - sqeuclidean
      - cosine
      - cityblock
      otlabelpropadapter__n_iter_max:
      - 100
      otlabelpropadapter__reg:
      - null
      - 0.1
      - 1.0
