dataset:
- AmazonReview
solver:
- CORAL:
    param_grid:
    - coraladapter__assume_centered:
      - false
      - true
      coraladapter__reg:
      - auto
      finalestimator__estimator_name:
      - SVC_C1000.0_Gamma0.001
