dataset:
- Office31
solver:
- CORAL:
    param_grid:
    - coraladapter__assume_centered:
      - false
      - true
      coraladapter__reg:
      - 1.0e-06
      finalestimator__estimator_name:
      - LR_C0.01
