dataset:
- Phishing
solver:
- CORAL:
    param_grid:
    - coraladapter__assume_centered:
      - false
      - true
      coraladapter__reg:
      - 1.0e-06
      finalestimator__estimator_name:
      - XGB_subsample0.8_colsample0.65_maxdepth20
