dataset:
- AmazonReview
solver:
- PCA:
    param_grid:
    - finalestimator__estimator_name:
      - SVC_C1000.0_Gamma0.001
      pca__n_components:
      - 1
      - 2
      - 5
      - 10
      - 20
      - 50
      - 100
