dataset:
- Simulated
solver:
- PCA:
    param_grid:
    - finalestimator__estimator_name:
      - SVC
      pca__n_components:
      - 1
      - 2
      - 5
      - 10
      - 20
      - 50
      - 100
